set_service_mode:
  name: Service Mode
  description: Sets the panel to service mode. Only applicable for Nixie controllers.
  fields:
    setting:
      name: Timeout
      description: The timeout in minutes. 0 puts the panel into service mode indefinitely.
      required: false
      example: "0"
      selector:
          number:
            min: 0
            max: 59940
            unit_of_measurement: minutes

set_auto_mode:
  name: Auto Mode
  description: Returns the panel to auto mode and resumes schedules. Only applicable for Nixie controllers.
